### ISSUE TITLE
qa-replace in header doesn't show board title

### ISSUE THREAD

**Issue by lc-guy** [ccd0/4chan-x#1390] opened 2017-05-28 20:38 UTC
![](http://gateway.glop.me/ipfs/QmWo22LyQi6DkKeTzb3s69hXN75Uvr5WF1z1t3VACB69cr/TApzZz.png)

v1.13.9.3
oneechan also used

**Comment by saxamaphone69** [comment] 2017-05-28 23:35
https://github.com/ccd0/4chan-x/issues/1366#issuecomment-301650449

**Comment by lc-guy** [comment] 2017-05-29 09:46
Whoops
>I've reported this inconsistency to them.
Anyway, it seems that hasn't been updated since then, so maybe a hotfix of some sorts could be put in place?

**Comment by ccd0** [comment] 2018-01-24 18:49
Closing as duplicate of #384.

**Closed by ccd0** 2018-01-24 18:49 UTC
Labels: merged or duplicate
