### ISSUE TITLE
Quick Reply post button gets stuck on 1 second "countdown"

### ISSUE THREAD

**Issue by forbjok** [ccd0/4chan-x#1355] opened 2017-05-06 18:47 UTC
For about a week now, the post button has been frequently getting stuck on a permanent 1 second countdown. I don't know what exactly triggers it, as I usually just notice it when I try to post something and find that the button is just stuck on "1" even though there is no active posting cooldown. Clicking it when it's stuck like this does nothing. Refreshing the page is the only way to fix it as far as I can tell.
This happens all the time, and needless to say it's extremely annoying. (just as an example, I just checked the QR dialogs on 6 threads I keep open - out of them, 3 of them were stuck on "1")

I'm using Firefox 53.0 64-bit.

**Comment by ccd0** [comment] 2017-05-07 14:21
Duplicate of #1323.
Also, please specify the version of 4chan X you're on.

**Closed by ccd0** 2017-05-07 14:21 UTC
Labels: merged or duplicate
