### ISSUE TITLE
Menu entry for Sauce

### ISSUE THREAD

**Issue by arrnonymous** [ccd0/4chan-x#1142] opened 2016-10-09 15:58 UTC
Mockup:
![image](https://cloud.githubusercontent.com/assets/22729309/19221764/d6ae7b1e-8e1f-11e6-9137-ad0faa32cae0.png)

**Comment by ididntknowicoulddothatXD** [comment] 2016-10-09 18:03
Would support it but only if it stay optional.

**Comment by ccd0** [comment] 2016-10-09 18:09
Duplicate of #391. No idea when it might happen, but a pull request implementing it would certainly be welcome.

**Closed by ccd0** 2016-10-09 18:09 UTC
Labels: merged or duplicate
