### ISSUE TITLE
[Feature Request] Add auto-watch based on regex

### ISSUE THREAD

**Issue by YfheA3r** [ccd0/4chan-x#2361] opened 2019-07-15 21:24 UTC
It whould be nice to have something similar to the filter system but that instead of hiding the thread it add it to the watcher

**Comment by YfheA3r** [comment] 2019-07-16 17:08
I tried to implement it:
https://github.com/YfheA3r/4chan-x/commit/e886f590da493697fc9b4cf9c6c403ac6e21252c
Since i don't really know CoffeeScript for the most part i just copy pasted code from the filtering system

It does work but there are problems that i'm not able to resolve:
-It doesn't remove auto-watched threads when you remove the regex
-It test the regex agains every post instead of every thread

**Comment by ccd0** [comment] 2019-07-16 17:50
Copypasting huge chunks of code like that is bad design. Instead you should edit the `Filter` feature to add this. You could indicate that a filter should watch rather than hide a thread by adding ";watch" to the end, like is already done with ";highlight" and ";notify".

**Comment by ccd0** [comment] 2019-07-16 17:52
Also, this is a duplicate of #1471 so further discussion should go there.

**Closed** 2019-07-16 17:52 UTC
Labels: merged or duplicate
