### ISSUE TITLE
[Suggestion] Make board list go back to normal on 4channel

### ISSUE THREAD

**Issue by GMLW** [ccd0/4chan-x#2146] opened 2018-11-24 07:40 UTC
I'm sure I'm not the only one annoyed about the board list being shrunk on the SFW boards, so I think a toggle to revert the board list back to normal would be useful. I could do it by adding each board into the custom board navigation list manually, but that's a pain and having a toggle that did it for me would be really nice.

**Comment by saxamaphone69** [comment] 2018-11-24 08:13
Duplicate of #2137.

**Closed** 2018-11-25 07:10 UTC
Labels: merged or duplicate
