### ISSUE TITLE
Board filter: "except" tag

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#559] opened 2015-10-31 20:49 UTC
Filters are set globally unless specified. I, for example, filtered posts that contain "dubs", etc.
Now, on boards like /a/ this is obviously a double-edged sword. There should be a way to exclude certain boards if set. 

Something like "/dubs/i;except:a,s4s" would make things easier; otherwise I'd have to specify which boards I want to exclude manually and that's just too bothersome as of now, imo.

**Comment by ccd0** [comment] 2015-11-04 05:03
duplicate of #439

**Closed by ccd0** 2015-11-04 05:03 UTC
Labels: duplicate
