### ISSUE TITLE
Menu option to delete post doesn't work well

### ISSUE THREAD

**Issue by qbb** [ccd0/4chan-x#311] opened 2015-01-31 14:30 UTC
Right after you post it doesn't show the cooldown and if you try deleting it says you can't delete it, then some seconds later, when you close the menu and reopen, you get the (60) cooldown. It also has some other issues like the cooldown being finished and you having to wait 1 more second before it works, etc.
I think this feature should be completely refactored. And it would be nice in the process if it got the behavior as posting, that when you click on the cooldown, it gets an "auto" setting that automatically does the action once the cooldown is over.
Thanks a lot for your 4chan X, it's the best we ever had!

**Comment by qbb** [comment] 2015-02-07 19:40
bump

**Comment by ccd0** [comment] 2015-02-22 23:33
This is something I've wanted to do for a while, but have never gotten around to.  Pull requests to implement this would be very welcome.  Closing as a dupe of #167.

**Closed by ccd0** 2015-02-22 23:33 UTC
Labels: duplicate
