### ISSUE TITLE
Error fetching archive data

### ISSUE THREAD

**Issue by bluefiberbread** [ccd0/4chan-x#2069] opened 2018-09-19 17:23 UTC
"Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error" 

Whenever I open a thread, this pops up.

**Comment by Vulgaris-Viridis** [comment] 2019-12-29 16:13
Here as well..

**Comment by ccd0** [comment] 2019-12-30 05:33
@Vulgaris-Viridis
Your issue is likely due to #2520 which is fixed now.

**Comment by Vulgaris-Viridis** [comment] 2019-12-30 22:09
> Your issue is likely due to #2520 which is fixed now.
Hi, @ccd0 I can confirm it's fixed, much appreciated!

**Closed** 2023-04-30 11:49 UTC
