### ISSUE TITLE
Tab icon doesn't refresh

### ISSUE THREAD

**Issue by instagramtest** [ccd0/4chan-x#2190] opened 2018-12-30 20:18 UTC
If a thread is archived the tab icon fails to indicate it (by changing colors to red). I've tested most of the recent versions and as fas as I can tell this issue was introduced with .5.2

Using Firefox 64

**Comment by TwilightSkyline** [comment] 2019-01-03 02:13
similar issue here. for me, it's only the blue read favicon. i checked in the advanced settings and the image for it seems to be missing or broken. this is the same for all favicon themes. see if you have similar results.

**Comment by AirplaneRandy** [comment] 2019-01-11 03:45
Same here. I shitpost all the time and I always have to check the thread to see if it was deleted. It was faster previously to just see if the icon turned red.

**Comment by beriah** [comment] 2019-01-13 13:33
https://github.com/ccd0/4chan-x/issues/2039

**Comment by ccd0** [comment] 2019-01-26 06:12
Confirmed, will fix. #2039 appears to be unrelated.

**Closed** 2019-07-18 06:45 UTC
Labels: bug
