### ISSUE TITLE
Blue boards not getting the .current css class applied

### ISSUE THREAD

**Issue by cercos** [ccd0/4chan-x#3439] opened 2024-01-27 14:47 UTC
I believe the issue is the recent change from 4channel.org urls back to 4chan.org for blue boards.  The board-list is generating 4channel.org urls still and it redirects to the 4chan.org url and whatever method is marking current urls is not marking the blueboards because of the redirect.

**Comment by saxamaphone69** [comment] 2024-11-02 11:52
Closing as a duplicate of #3424.

**Closed by saxamaphone69** 2024-11-02 11:52 UTC
