### ISSUE TITLE
Weird catalog behavior

### ISSUE THREAD

**Issue by esgwpl** [ccd0/4chan-x#291] opened 2015-01-13 13:38 UTC
As of 1.9.20.2 the catalog has been behaving weirdly on my end, sometimes it doesn't show any threads at all, reloading the page does fix it though.

![screenshot - 01132015 - 08 29 54 pm](https://cloud.githubusercontent.com/assets/10489620/5721395/c4053602-9b63-11e4-9a01-f3098ec1b722.png)

**Comment by ccd0** [comment] 2015-01-13 15:25
It could just be connection problems with 4chan.

Any error messages in the browser console?

**Comment by whoknows22** [comment] 2015-01-13 19:49
Been having this issue since yesterday too. Also happens on 1.9.19.11. Does not happen on 4chanX's catalog, only when using 4chan's default one.

I'm not too familiar with using the browser console but the only error I get is this:

TypeError: a is null
catalog.959.js:1

**Comment by ccd0** [comment] 2015-01-13 20:56
Sorry, didn't notice you were using the native one.

Can you check if it happens with 4chan X disabled?

**Comment by whoknows22** [comment] 2015-01-13 22:16
Can't say for sure since it's random, but I'm almost certain it doesn't. It seems to happen on an average of 5-6 refreshes, sometimes several times in a row. Disabled 4chanX, refreshed it 50+ times, didn't happen once.

**Comment by bakugo** [comment] 2015-01-13 22:44
This is caused by a missing `settingsWindowLinkBot` element, it's normally created by `cloneTopNav` but 4chan X removes it ([here](https://github.com/ccd0/4chan-x/blob/f8d0939953ec812fce45150477c0c95d31170201/src/General/Header.coffee#L98))

**Comment by ccd0** [comment] 2015-01-14 03:33
@bakugoI thought it might be that.  It should be fixed now assuming that was the problem.

**Comment by ccd0** [comment] 2015-01-20 00:02
This working for everyone now?

**Comment by whoknows22** [comment] 2015-01-20 17:57
Yeah, it's been fine since that fix last week.

**Comment by ccd0** [comment] 2015-01-20 23:35
Thanks for confirming.

**Closed by ccd0** 2015-01-20 23:35 UTC
Labels: conflict
