### ISSUE TITLE
NoScript captcha broken?

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2500] opened 2019-12-15 13:45 UTC
Having it on seems to return 
"Could not connect to the reCAPTCHA service.

Please check your internet connection and reload to get a reCAPTCHA challenge."
This wasn't happening about 8 hours ago. Normal captcha seems to work but fuck the normal captcha. Tried it on both Pale Moon and Vivaldi but it doesn't work on either.

**Comment by ihebchagra** [comment] 2019-12-15 14:06
Having the same issue on qutebrowser through its builtin greasemonkey
normal captchas seem to work
Also disabling javascript entirely yields the same result. I think we can conclude the issue is not from 4chan-x but either 4chan or recaptcha
![2019-12-15-15:03:08-298x416](https://user-images.githubusercontent.com/51883835/70863798-1ea00300-1f4c-11ea-9fe8-3154a939e103.png)

**Comment by Jorge9811** [comment] 2019-12-15 14:10
Same. NoScript Captcha is broken on my end, but the regular shitty Captcha is working normally in Firefox v71 with 4ChanX v1.14.15.0 on Violentmonkey.

**Comment by F0kT** [comment] 2019-12-15 14:19
Same. A pressing issue.

**Comment by thatguy344** [comment] 2019-12-15 15:03
I too am having this issue

**Comment by JackJohnJoe** [comment] 2019-12-15 15:52
it's happening

**Comment by AssCrab** [comment] 2019-12-15 17:17
Yeah, same issue.
Also Javascript ReCaptcha completely lags out the page. On larger threads it even enters an infinite spinner/loading loop that won't stop. This seems to be an issue with the way captcha is designed into the reply UI from what i've searched online regarding people experiencing captcha lagging out pages and overloading CPU. It's unusable.

**Comment by charisti5676** [comment] 2019-12-15 17:31
![image](https://user-images.githubusercontent.com/55940554/70866365-70a74f80-1f71-11ea-9630-779624dfc502.png)
Same here :(
Did it came to an end ?

**Comment by Davidj361** [comment] 2019-12-15 19:23
Same

**Comment by Pentaphon** [comment] 2019-12-15 19:32
It's orge

**Comment by stylechan** [comment] 2019-12-15 20:26
Both Clover and 4chan X seem to be affected by this, ReCaptcha is working fine outside these programs and on 4chan otherwise.

**Comment by isse101** [comment] 2019-12-16 01:34
https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0
hironigger blocked it on purpose probably in an attempt to get more people to buy 4chan passes

**Comment by cesfhiil** [comment] 2019-12-16 08:19
> https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0
the fallback works on my end

**Comment by Jorge9811** [comment] 2019-12-16 19:01
> https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0
This works. With 0 knowledge about programming, I tried to replace 4ChanX's old link with this one, but while the captcha does work in 4Chan trying to submit a post after completing the "challenge" gives an error about the captcha misfunctioning. FUCK Hiroshitmoot.

**Comment by charisti5676** [comment] 2019-12-16 20:09
small update guys, 
some fucking fat yannie with a tiny dick blocked it because he got nothing better to fucking do because he is a fucking smelly virgin
anyways they block the noscript captchas 

the noscript itself is working but for 4chan it some how disabled

**Comment by ranc4** [comment] 2019-12-16 22:48
i had a problem too like here in the past 2 months, were on any board well from what i checked mostly /g/ /v/ /pol/ noscript captchas on 4chin would let you post without solving another for 3 minutes after you posted, on the other boards you have a 60 sec wait between posts besides on /pol/.  /pol/ let u post replies for 3 minutes after solving a captcha with like maybe a 10 second wait.  since the past 2 months or something, everytime i done a noscript captcha, i had to immediately do another one if i tried to post another reply. no 3 min period.  it just asked you to solve another captcha. the ohter boards like /v/ and /g/ from what i checked, worked let u post for 3 min.  the regular captcha gives you a 3 minute post timer after that too.  
i dont even want to post on there, how the captchas were, they were so many like raping you on them and didnt care and wouuldnt slow them down either before they went to forcing 1 per post cause i was switching back and forth.  i had another problem before that kept no scripts from working for me until i gott it fixed, which was when they stopped old captchas and ramped up the fucking amount of nonstop fucking with you captchas after that.  
captchas the way they were are so fucking bad, i cant even stand to use the site.   captchas are just so fucking bad.  you get it right they claim ur wrong for nothing.  i complained to newegg on theirs, and they immediately said to me, how do you stop hackers then? 
so nonstop harrassment is going to fix bots..  it does nothing.  fuck it i dont care.  if there was no fucking internet the bots would nt have no where to post.

**Comment by Knatan** [comment] 2019-12-17 16:30
Jorge9811 and charisti5676 I hope this isn't the case.

1 thing I have observed with the regular recaptcha is it act differently depending on which browser you used.
If you use Google's own browser, the recaptcha would occasionally give you freebies, and allow you access to post without solving anything.
If you use Palemoon and other mozilla based browsers, the recaptcha would engage in a$$hole-mode and never give you any freebies.

The Noscript version recatpcha was the one that treated all browsers fair. It only asked you to solve a recaptcha once, and was benevolent that way. Unlike the regular recaptcha which tried to harass you if you used the wrong browser.
I hope this issue can be fixed somehow.

**Comment by Janaue** [comment] 2019-12-17 16:44
> 
> 
> > https://www.google.com/recaptcha/api/fallback?k=6LfBixYUAAAAABhdHynFUIMA_sa4s-XsJvnjtgB0
> 
> This works. With 0 knowledge about programming, I tried to replace 4ChanX's old link with this one, but while the captcha does work in 4Chan trying to submit a post after completing the "challenge" gives an error about the captcha misfunctioning. FUCK Hiroshitmoot.

i tried it too and I get the ''no valid captcha'' too, I do not understand why the browser or 4chan does not see the completed captcha. can @ccd0 fix this disaster ?

**Comment by Knatan** [comment] 2019-12-17 17:16
Here is another issue with regular recaptcha.
![Untitled](https://user-images.githubusercontent.com/1931284/71018685-39fc4100-20f9-11ea-9f8b-96a37d1fd7df.png)
It forces you to solve multiple recaptchas, and then accuse you are being a bot. (it will continue with this malicious shenanigan so long as you use a non-google browser)

This is why we desperately need the Noscript version to work.

**Comment by isse101** [comment] 2019-12-17 18:02
> Jorge9811 and charisti5676 I hope this isn't the case.
> 
> 1 thing I have observed with the regular recaptcha is it act differently depending on which browser you used.
> If you use Google's own browser, the recaptcha would occasionally give you freebies, and allow you access to post without solving anything.
> If you use Palemoon and other mozilla based browsers, the recaptcha would engage in a$$hole-mode and never give you any freebies.
> 
> The Noscript version recatpcha was the one that treated all browsers fair. It only asked you to solve a recaptcha once, and was benevolent that way. Unlike the regular recaptcha which tried to harass you if you used the wrong browser.
> I hope this issue can be fixed somehow.

Also, I use a Chromebook to browse 4chan occasionally and it almost always gives me freebies.

**Comment by hockeymikey** [comment] 2019-12-17 19:26
> 
> 
> Here is another issue with regular recaptcha.
> ![Untitled](https://user-images.githubusercontent.com/1931284/71018685-39fc4100-20f9-11ea-9f8b-96a37d1fd7df.png)
> It forces you to solve multiple recaptchas, and then accuse you are being a bot. (it will continue with this malicious shenanigan so long as you use a non-google browser)
> 
> This is why we desperately need the Noscript version to work.

This probably has something to do with the browser, like Firefox with privacy notracking features turned on.

**Comment by Dotty** [comment] 2019-12-17 20:58
Well yeah trying to patch that one in is going to malfunction. That key doesn't authorize anything on 4chan at all. It's just one that someone posted on 4chan; related to some other site or person.
Solving that one rewards whoever it's connected to, and could give access to whatever it's connected to; not 4chan.
Like it was just an example that non-JS captcha still works where the hosting site and Google allow; that it's not completely disabled like the old text Captcha V1 was.

**Comment by ranc4** [comment] 2019-12-17 21:27
> 
> 
> > Here is another issue with regular recaptcha.
> > ![Untitled](https://user-images.githubusercontent.com/1931284/71018685-39fc4100-20f9-11ea-9f8b-96a37d1fd7df.png)
> > It forces you to solve multiple recaptchas, and then accuse you are being a bot. (it will continue with this malicious shenanigan so long as you use a non-google browser)
> > This is why we desperately need the Noscript version to work.
> 
> This probably has something to do with the browser, like Firefox with privacy notracking features turned on.

oh yea right.  there code just doesnt work so yea duh its just your privacy features.  there is no such thing as what you claim, privacy.  its google intentionally not giving you the ok right answer here selection of options they give out. instead its haah were gonna LIE and say your wrong do it again and again and however many this goes on for or maybe the site owner I think setting these things up, and on timers too.  Dont give us this bullcrap that its just some privacy feature breaking their basic shit. ur comment has been debunked for ages and you still bring it out like just unsecure yourself and go along with whatever google says its just not human verified yet.

**Comment by AssCrab** [comment] 2019-12-17 22:35
@ Knatan
I'm using pre-Quantum FireFox now and I used to get freebies with noscript recaptcha and also still get freebies with the JS recaptcha. Only problem is that JS recaptcha, as stated before, really loves to lag and go into infinite spinner when threads become too long.

**Comment by zero733** [comment] 2019-12-18 01:29
Just wanted to thank you all for working on this. I've been using Chrome since the break but twenty minutes ago it locked me into an infinite loop of Next captchas.

**Comment by ccd0** [comment] 2019-12-18 18:18
I've verified on a test site that Google only allows the noscript version of captcha if the site owner sets the captcha difficulty to easy. This used to be mentioned in the documentation:

http://web.archive.org/web/20181022173702/https://developers.google.com/recaptcha/docs/faq#does-recaptcha-support-users-that-dont-have-javascript-enabled

**Comment by charisti5676** [comment] 2019-12-18 20:26
what did I wanted ? posting on the damn site? 

Fucking thanks mods I am not a robot whats the whole idea of the captcha ? The whole idea is to stop bots not humans

**Comment by Revemohl** [comment] 2019-12-18 23:59
And ironically enough, this change didn't affect bots at all. Thanks mods!

**Comment by ccd0** [comment] 2019-12-22 07:44
#2506:
> Using 4chan X (1.14.14.5) with Tampermonkey 4.5, Adblock 4.0.2, AdblockPlus 3.7 and uBlock Origin 1.23.0 in Chrome
> Turning "Force Noscript Captha" on results in "Could not connect to the reCAPTCHA service.
> 
> Please check your internet connection and reload to get a reCAPTCHA challenge."
> 
> Captcha works if I disable this option and reload page

valued-customer:
> I have the identical problem, except that there is no captcha at all if I don't force noscript captcha.  I can no longer post at all on 4chan, with or without 4chanx.    Using Opera.
> 
> ![4chanbroke](https://user-images.githubusercontent.com/59104486/71301411-82af3680-2353-11ea-99b5-9f75a46220fa.png)

**Comment by broski93** [comment] 2019-12-29 21:33
I'm having issues with JS captcha too. On relatively long threads (80+ posts) it doesn't load, or loads and then says connection lost, while at the same time causing cpu spikes and browser lagging/freezing. Disabling 4chanX makes me post easily.
I've seen a similar thread on /g/ with OP having the same problem, but nothing else. I'm using Firefox and Violentmonkey to run 4chanX.

**Comment by LtPatterson** [comment] 2019-12-30 15:13
This is also affecting Clover for 4chan. Several issues posted over on that repo, no response from the dev. Fucking annoying.

**Comment by AssCrab** [comment] 2020-01-05 22:56
@ broski93
Yeah. I did the performance test in the inspect element thing.
The giant canyon in the pic is when i opened the captcha, and then closing the captcha brought everything back to normal. It was a major performance spike from captcha alone only when using 4chan-X.

**Comment by Z3ROGRAV1TYx** [comment] 2020-01-22 19:31
Same issue on Firefox running Violentmonkey, latest everything.
Disabling Noscript fixes, but I don't want to have to do that.
Kuroba is also affected for me.

**Comment by Revemohl** [comment] 2020-07-31 05:33
All of a sudden, it seems to be working again now. Let's just hope this wasn't an accident from Hiro's part.

**Closed** 2023-05-08 10:53 UTC
Labels: upstream, anonymous report
