### ISSUE TITLE
Unable reply or make threads using 4chan X dialog window for the last 3 days. Isolated Issue?

### ISSUE THREAD

**Issue by cardgum** [ccd0/4chan-x#3330] opened 2023-02-12 16:58 UTC
4chanX
TamperMonkey
Firefox
Windows 10

Sometimes this issue did happen in the past, but it lasted only the morning, but now it's been 3 days. Whenever I try to reply or make a thread using 4chanX, it'll report that the post was successful or the thread has been created but really, nothing has been done. When a thread is "made", a new tab will popup with a random thread chosen from the catalogue, usually it's one of the newest threads, not my own.

I've tested this using the Chrome 4chanX and I was able to reply successfully using 4chanX. So this is likely an issue with Firefox on my end as I see no other thread reporting this. My only fix is to reset or clean my Firefox install. I'm curious as to why this is affecting 4chan X's ability to make replies despite nothing changing from the last day.

**Comment by cardgum** [comment] 2023-02-12 17:14
Tested in Waterfox. Was able to reply just fine.
Definitely an isolated issue with Firefox, a strange one.

**Comment by cardgum** [comment] 2023-02-12 17:24
Did a refresh on Firefox. Issue still persists.
Will be using Waterfox instead in the meantime.

**Comment by TeeraAskort** [comment] 2023-02-14 17:13
This issue seems to be related with the violentmonkey extension, I've tested it with greasemonkey and could reply fine and my posts appeared on the threads.

**Comment by Burnil** [comment] 2023-02-16 12:18
Same issue. Windows 10, Firefoc 110.0 Violentmonkey 2.13.9.

**Comment by Hakkin** [comment] 2023-02-19 21:43
It's caused by a missing form value in the quick reply POST request, you can fix it by adding `MAX_FILE_SIZE: QR.max_size,` @ line 24,738 in the userscript (after `formData = {`)

**Comment by paradox460** [comment] 2023-03-03 07:48
Fixed in https://github.com/ccd0/4chan-x/releases/tag/1.14.22.2

**Closed by paradox460** 2023-03-03 07:48 UTC
